env:
  global:
  # - Maybe a token key or something
language: node_js
notifications:
  email: false
services:
  # - postgresql
node_js:
  - "7"
script:
  - npm test
after_success:
  - npm run coverage
  - coveralls < coverage/lcov.info